version: "3.3"

services:
   mongodb:
      image: mvertes/alpine-mongo
      restart: always
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017

